### ISSUE TITLE
US1: Project General Requirements

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#13]
As a developer, I can understand the goals of the site so that development decisions can be made accordingly

EPIC #1 

Acceptance criteria
1. Given that I am a developer I will understand what the site will achieve 
2. Given that I am a developer I will understand the logic and database models needed
3. Given that I am a developer I will be able to complete a project plan and user stories

Tasks
- [x] Write goals for site
- [x] Create wireframes of front end to identify components
- [x] Create Database schema to illustrate the entity relationships
- [x] Create logo
- [x] Research icons and color scheme
- [x] Gather graphics to be used
- [x] Create Repo
- [x] Create Project board
- [x] Create Epics and User Stories
- [x] Create Labels and Milestones
- [x] Create Storypoints
- [x] Create Labels according to the MoSCoW system
- [x] Create Readme template

Story Points = 1

**Comment by rstan-dev** [comment]
Purpose & Target Audience

GarageGuru is a  collaborative Job Card Management system for a vehicle service centre.  The staff can register and log in to record each job, write notes about the job, set a due date, assign the job to a colleague, add a photo of the job, leave comments about a job and add a job to a watch list.

Goals for the first-time user
1.  To understand instantly what the site is for and how to register or login
2.  To be able to easily navigate the site with a clear intuitive interface
3.  To easily see all jobs, their own jobs and assigned jobs.
4. To easily search or filter jobs by status etc
5. To easily be able to leave comments about a job
6. To easily watch a job as it progresses through the system

Goals for the returning user
1.  To easily know if they are logged in or out
2. To return to the main page with the summary status of the jobs in the system

Goals for the site owner
1. To be able to moderate comments or job details
2. To be able to create, edit or delete, users, profiles, jobs and comments on the backend

**Comment by rstan-dev** [comment]
Icons and Color Scheme
Dark Grey Font Color - 

Icons on fontawesome
- All Jobs - <i class="fa-solid fa-car"></i>
- My Jobs - <i class="fa-solid fa-clipboard-list"></i>
- Add Job - <i class="fa-solid fa-circle-plus"></i>
- Assigned Jobs - <i class="fa-solid fa-people-group"></i>
- Login - <i class="fa-solid fa-right-to-bracket"></i>
- Log out - <i class="fa-solid fa-right-from-bracket"></i>
- Register - <i class="fa-solid fa-user-plus"></i>
- Profile - <i class="fa-solid fa-circle-user"></i>

Pending - <i class="fa-solid fa-bell-concierge"></i>
Underway - <i class="fa-solid fa-hourglass-half"></i>
Completed - <i class="fa-solid fa-flag-checkered"></i>

Job type
details
Created
Updated
Due date
Assigned to
Status

Pencil
Eyes
Speech bubble
