### ISSUE TITLE
US2: Setup Repo

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#14]
As a developer, I will set up the repo and install the necessary packages  so that I can start building the initial models to view on the React front-end

EPIC #1 

Acceptance criteria
1. Given that I am a developer I will connect the front end to the back end and set the settings appropriately

Tasks
- [x] set-up according to: https://docs.google.com/document/d/1LCLxWhmW_4VTE4GXsnHgmPUwSPKNT4KyMxSH8agbVqU/edit#heading=h.mpopj7v69qqn
- [x] Update settings.py
- [x] Create ElephantSQL database
- [x] Create cloudinary link
- [x] Create Secret Keys
- [x] Create env.py and git.ignore

Story Points = 1

**Comment by rstan-dev** [comment]
ElephantSQL created and tested, DEV db set to sqlite3 else use ElephantSQL DB
