### ISSUE TITLE
US3: Profiles Model

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#15]
As a superuser I can login to the admin panel so that I can manage users and other parts of the system as it develops

EPIC #2

Acceptance criteria
1. Given that I am a superuser, I can log in to the admin area of django
2. Given that I am a superuser, I can create, edit and delete other users
3. Given that I am a superuser, I can create, edit and delete name, bio and image fields on my profile

Tasks
- [x] Create Profile model with name, bio and image field linked to cloudinary
- [x] Create urls.py
- [x] Register admin.py
- [x] Create Serializers
- [x] Use django signals to trigger a post_savefunction to create a profile
- [x] Create views.py
- [x] Ensure there is a default image that is displayed when a user has not uploaded a picture 
- [x] Login and check profile with default image
- [x] Create additional profile with own image

Story Points = 2
