### ISSUE TITLE
US4: Jobs Model

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#16]
As a superuser, I can manage a Job Card so that I can create, update, delete and view the details of the jobs I wish to display

EPIC #3

Acceptance criteria
1. Given that I am a superuser I can create a Job in the admin portal and view the JSON data
2. Given that I am a superuser I can edit a Job in the admin portal and view the JSON data
3. Given that I am a superuser I can delete a Job in the admin portal and view the JSON data
4. Given that I am a superuser I can view a Job by id in the admin portal and view the JSON data

Tasks
- [x] Create Job model with Job Selector, description field, created date, updated date, due date, assigned user field, status choice field and image field linked to Cloudinary
- [x] Ensure there is a default image that is displayed when a user has not uploaded a picture 
- [x] Create 1 Job card
- [x] Create Get and Put functions
- [x] Create Edit and Delete functions
- [x] Create serializers
- [x] Link Job card to user
- [x] Ensure Job card owner can edit, else ReadOnly
- [x] make choices show a default. 
- [x] Add image_filter to JobSerializer
- [x] Add admin views and filters backend
- [x] Write Jobs Tests

Story Points = 2

**Comment by rstan-dev** [comment]
next up:  make choices show a default.  Add image_filter to JobSerializer

**Comment by rstan-dev** [comment]
Serializer links Job Card to owner = ReadOnly field

**Comment by rstan-dev** [comment]
assigned_to uses PK field - dropdown selector in DRF form tested as working

**Comment by rstan-dev** [comment]
Add due_date to model and test

**Comment by rstan-dev** [comment]
to continue: establish why this test is failing

def test_user_can_update_their_own_job_card(self):
        self.client.login(username='testuser1', password='testpw1234')

        response = self.client.put(
            '/jobs/1',
            {
                'job_type': 'Major Service',
                'job_details': 'NEW test details',
                'status': 'Pending',
                'assigned_to': 2
            },
            content_type='application/json'
        )

        # Ensure that the job is updated in the database
        job = Job.objects.filter(pk=1).first()

        # Add debugging print statements
        print(f'Updated Job Details: {job.job_details}')
        print(f'Response Content: {response.content}')

        # Create the serializer after the job is updated
        serializer = JobSerializer(job, context={'request': self.client._request()})

        # Print the serialized data for debugging
        print(f'Serialized Data: {serializer.data}')

        # Check if the response status code is as expected
        self.assertEqual(response.status_code, status.HTTP_200_OK)

        # Check if the job details were updated as expected
        self.assertEqual(job.job_details, 'NEW test details')
