### ISSUE TITLE
US5: Create NavBar

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#17]
As a website user I can view the basic navbar so that I can easily navigate the website on desktop and mobile

EPIC #4 

Acceptance criteria
1. Given that I am website user I will see a fully responsive NavBar at the top of the site at all times
2. Given that I am website user, I will see icons for Profile, Log in, Log Out, Register, Staff, Add Job, My Jobs, All Jobs and the Garage Guru Logo

Tasks
- [x] Install react 
- [x] import Bootstrap cdn
- [x] import fontawesome
- [x] Import Google Fonts
- [x] add favicon to index.html
- [x] Create Bootstrap NavBar component
- [x] Add icons and burger menu for mobile view
- [x] create base css
- [x] create navbar css

Story Points = 2

**Comment by rstan-dev** [comment]
nvm install 16 && nvm use 16
npm start
