### ISSUE TITLE
US6: Link NavBar

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#18]
As a website user  I can navigate each page seamlessly  so that I do not need to wait for page refresh

EPIC #4 

Acceptance criteria
1. Given that I am a webiste user, each NavBar icon will link to a relevant page without refresh

Tasks
- [x] Instal react-router-dom
- [x] Create and Link Routes in App.js
- [x] Create placeholder pages
- [x] Create Page Not Found
- [x] drop down nav should be white

Story Points = 1

**Comment by rstan-dev** [comment]
Userstory completed
