### ISSUE TITLE
US7: User Login Frontend

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#19]
As a website user  I can login  so that I can access all the functions of the site, and I can easily see if I am logged in or not

EPIC #5 

Acceptance criteria
1. Given that I am a website user, the landing page will take me to a login page if I am not already logged in.
2. Given that I am a website user, I will see my username when I log in
3. Given that I am a logged in User, the NavBar icons will change to allow functions only available to a logged in user - All Jobs, My Jobs, Add Job, Assigned Jobs, Watched Jobs, Sign Out

Tasks
- [x] Install axios library
- [x] create API folder
- [x] Create axiosdefaults.js
- [x] Create pages/auth folder
- [x] Create loginpage.js
- [x] Install dj-rest-auth
- [x] Create LoginForm.js
- [x] create eventhandlers for login in

Story Points = 1
