### ISSUE TITLE
US9: User Registration FrontEnd

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#21]
As a website user  I can register for an account  so that I can access the functions of the site

EPIC #5 

Acceptance criteria
1. Given that I am a website user, I can register for an account through a dedicated form
2. Given that I am a newly registered user, I can log in with the new credentials 
3. As a webiste user I will be notified of entering any incorrect information

Tasks
- [x] Create RegisterForm.js
- [x] Create handleChange and handleSubmit functions to '/dj-rest-auth/registration/
- [x] Redirect user to sign in form after successfully signing in
- [x] Add alerts to notify user 
- [x] Link Register form to Login form

Story Points = 1
