### ISSUE TITLE
US11: View Profile Page frontend

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#23]
As a logged in User I can view my profile so that I can see the details I have entered about myself

EPIC #6 

Acceptance criteria
1. Given that I am a logged in user, I can view my username, name, bio and profile image

Tasks
- [x] Create profile.js
- [x] Create CurrentUserContext.js
- [ ] Create ProfileDataContext.js

Story Points = 2

**Comment by rstan-dev** [comment]
Basic Profile Page retrieved.
ProfileDataContext not required at this time
