### ISSUE TITLE
US12:  Edit Profile Page frontend

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#24]
As a logged in User I can edit my profile so that I can change my personal info

EPIC #6 

Acceptance criteria
1. Given that I am a logged-in user I can edit my name, bio and photo

Tasks
- [x] Create EditProfile.js
- [x] Populate Edit form
- [x] Create EditProfile Styles
- [x] Setup Route
- [x] Link profile Page to Edit Page
- [x] Add Update and Cancel buttons
- [x] Add alerts and confirmation
- [x] On clicking the update button - display a confirmation for the user to click to proceed
- [x] When the update function has completed, display a success message"
- [x] Prevent access to Profile and Edit Profile links when user is not logged in

Story Points = 2

**Comment by rstan-dev** [comment]
Next up:  update photo, add alters and success message, Cancel button to redirect to profile page, redirect after successful update

**Comment by rstan-dev** [comment]
redirects are a bit glitchy but it works so far
