### ISSUE TITLE
US14: Update Username frontend

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#26]
As a logged in User I can change my username so that I can change me username if I want to

EPIC #6 

Acceptance criteria
1. Given that I am a logged in user I can change my username to a new one, and receive a 

Tasks
- [x] Create Username form - Modify ChangePasswordForm
- [x] Link to Change Username button
- [x] Add route to app.js
- [x] add state, handleChange, handleSubmit, update html attribs
- [x] add useEffect for !currentuser
- [x] add errors and alerts
- [x] add sucess message
- [x] test functionality

Story Points = 2
