### ISSUE TITLE
US15: View Jobs

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#27]
As a logged in User I can click on the All Jobs button in the NavBar so that I can see all the jobs in the system

EPIC #7 

Acceptance criteria
1. Given that I am a logged-in user, the All Jobs Button will display a list of Job Cards
3. Given that I am a logged-in user, I will see the number of jobs indicated under pending, Underway and Completed, and these will change when I change the status"3.

Tasks
- [x] Create JobPage component to display JobCard component   
- [x] Create JobCard.js component
- [x] Create css module
- [x] Create AllJobsPage.js incorprate JobCard component
- [x] Display JobCard on All Jobs Page
- [x] Add Status Box 
- [x] Add InfiniteScroll component for when there are more than 10 job cards
- [x] Add pagination to settings.py in drf_api
- [x] Add logic to update the counter on the filter dashboard when the Status Changes"

Story Points =2

**Comment by rstan-dev** [comment]
moved to sprint 4
