### ISSUE TITLE
US16: Search All Jobs

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#28]
As a logged in User I can enter a query in the search bar so that I can find a job easily

EPIC #7 

Acceptance criteria
1. Given that I am a logged-in user, I can search by Job type, details, assigned to and status

Tasks
- [x] Add search bar feature
- [x] Create filters
- [x] Add filtering to DRF and Jobs View
- [x] Update pagination to reflect Status Counts for search results
- [x] Add logic to handle search query in axiosReq
- [x] Add conditional logic to handle status results

Story Points = 2

**Comment by rstan-dev** [comment]
Moved to Sprint 4
