### ISSUE TITLE
US 17: Filter jobs

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#29]
As a logged in User I can filter the job cards	so that I can display them in the order I want

EPIC #7 

Acceptance criteria
1. Given that I am a logged-in user, I can filter by Pending, Underway, Completed at the top of the All Jobs Page
2. Given that I am a logged in User, I can filter by Most recently added, most recently updated and by due date

Tasks
- [x] Build "Filter by" section
- [x] Add logic to filter by each status, according to recently created, last_updated and due date
- [x] Fix date and time formatting in JobSerializer
- [x] create buttons for each date filter and link to api call

Story Points = 2

**Comment by rstan-dev** [comment]
moved to sprint 4

**Comment by rstan-dev** [comment]
styling filter buttons is still needed
