### ISSUE TITLE
US18: Add Job

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#30]
As a logged in User I can click on the Add Job button in the NavBar	so that I can add the Job details to a form and save to the database

EPIC #8 

Acceptance criteria
1. Given that I am a logged-in user, I can open a blank job form, select the Job Type from a drop-down, add details, select a due date, assign the job to one of the users in the list and select the Status, which defaults to Pending

Tasks
- [x] Set Route
- [x] Display Job type Choices dropdown
- [x] Selectd a Due Date from a date selector(today is the default, past dates cannot be selected)
- [x] Display  Assigned To dropdown of all the registered users - (the logged-in user is the default)
- [x] Display the Status dropdown - Pending is the default
- [x] When add function has been completed display a success message

Story Points = 2

**Comment by rstan-dev** [comment]
styling needs to be completed
