### ISSUE TITLE
US19: Edit Job Card

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#31]
As a logged in User, and creator of a job, I can click on the pencil icon on the job card so that I can edit the Job Card details

EPIC #8 

Acceptance criteria
1. Given that I am the creator of a job card, I can edit or update any of the fields
2. Given that I have edited the job card, I will get a confirmation message and Button to proceed or cancel before submitting
3. Given that I have edited the job card, I will get a success message after it has been submitted and I will be redirected back to the page I was on

Tasks
- [x] Create EditJobPage.js
- [x] Link component to pencil icon
- [x] Populate form with existing details
- [x] Check if Logged in User is owner in order to display pencil icon
- [x] On clicking the update button - display a confirmation for the user to click to proceed
- [x] When update function has been completed display a success message
- [ ]

Story Points = 2
