### ISSUE TITLE
US20: Delete a Job

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#33]
As a logged in User, and creator of a job,  I can click on the pencil icon on the job card  so that I can delete the Job Card details

EPIC #8 

Acceptance criteria
1. Given that I am the creator of a job card, I can delete the entire job card
2. Given that I have clicked the Delete button, I will see a confirmation message prior to execution"

Tasks
- [x] Display Delete button
- [x] Write logic to delete a job
- [x] On clicking the delete button - display a confirmation Modal for the user to click to proceed or cancel
- [x] When the delete function has completed display a success message to the user
- [x] Return user to the last page they were on.

Story Points = 2

**Comment by rstan-dev** [comment]
BOOK MENTOR MIDWAY MEETING HERE
