### ISSUE TITLE
US21: View Job Comments

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#34]
As a logged-in user | I can click on the comments bubble  so that I can view all the comments that have been made about the job

EPIC #9 

Acceptance criteria
1. Given I am a logged in user, I can see all comments about a specific job
2. Given I am any logged in user I can see when a comment was made and who made it
3. Given I am a logged-in user, comments will be displayed in order of most recently created
4.

Tasks
- [ ] Create comments model
- [ ] Display comment icon on each job card
- [ ] Open list of comments in Modal
- [ ]
- [ ]

Story Points = 2

**Comment by rstan-dev** [comment]
display count of comment next to the comment bubble - this is moved to small items as COULD HAVE
pen list of comments in Modal - moved to small items as COULD HAVE
