### ISSUE TITLE
US21: Add comment

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#35]
As a logged in user  I can add a comment so that I can leave any comments about a particular job

EPIC #9

Acceptance criteria
1. Given I am any logged in user, I can click on the chat bubble on a job card add a comment about a specific job

Tasks
- [x] Create comment Model, serilaizer and view - update Installed Apps in settings
- [x] Create url path
- [x] Register model in admin adn create test comment in backend console.
- [x] Write untitests to confrim expected behaviour
- [x] Create AddCommentForm.js component
- [x] Create Comment Component to display comments
- [x] Create post request to add comment
- [ ] Link component to Modal - when user clicks comment bubble a modal opens with all of the comments displayed

Story Points = 2

**Comment by rstan-dev** [comment]
Link component to Modal - when user clicks comment bubble a modal opens with all of the comments displayed - moved to small items - Could Have
