### ISSUE TITLE
US23: Edit Comment

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#36]
As a logged in User, and creator of a comment,  I can click on the pencil item of a comment I have written  so that I can update it if I want to

EPIC #9 

Acceptance criteria
1. Given that I am the creator of a comment I can edit or update the comment

Tasks
- [ ] Create EditCommentForm.js
- [ ] Modify comments code from Moments project
- [ ] Create logic to handleChange and handleSubmit
- [ ] add form to display text edit area
- [ ] Style form to match AddComments area
- [ ] import component to CommentSection
- [ ] Test comment update

Story Points = 2
