### ISSUE TITLE
US24: Delete Comment

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#37]
As a logged in User, and creator of a comment,  I can click on the pencil item of a comment I have written  so that I can delete it if I want to

EPIC #9 

Acceptance criteria
1. Given that I am the creator of a comment, I can delete the entire comment
2. Given that I have clicked the Delete button, I will see a confirmation message prior to execution"
3. Given that I am not the creator, I cannot delete the comment

Tasks
- [x] Add handleDelete function to EditCommentForm
- [x] Display Delete button
- [x] On clicking the delete button - display a confirmation for the user to click to proceed, insert confrimationModal
- [x] When the delete function has completed display a success message
- [x] Decrement the Comment count after successful delete
-

Story Points = 2

**Comment by rstan-dev** [comment]
Comment count decrements after reload.  Further work needs to be done to call comment_count from backend.  Adding this to small items
