### ISSUE TITLE
US25: Watch Jobs

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#38]
As a logged-in user | I can click on the eyes icon on a job card so that I can add it to my watch list where I can keep an eye on a job

EPIC #10 

Acceptance criteria
1. Given that I have clicked on the eyes icon I will see the job card appear in my Watch Job list
2. Given that I click the eyes icon again, it will remove it from my watch Jobs list
3.

Tasks
- [ ] Create watch model
- [ ] Create filter for watching
- [ ] Add to Routes
- [ ]
- [ ]

Story Points = 1
