### ISSUE TITLE
US27: Edit Invoice Details on Job Card

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#39]
As an Owner or Assigned person of a Job Card I can edit invoice details on a job card so that I can edit any of the details of the invoices for a job

EPIC #10 

Acceptance criteria
1. Given that I am the owner of a job - I will see the Edit Invoice Details Button in the Job Card 
2. Given that I am the Assigned user of a job - I will see the Edit Invoice Details Button in the Job Card 
3. Given that I am a general user I will only see invoice details if they have been populated

Tasks
- [x] Create EditInvoicePage
- [x] Link JobCard Edit Invoice button
- [x] Add alerts and success message
- [x]  Add conditional - If Invoice display View Invoice or "No Invoice to display. Only Users who created a job or are assigned a job can add an invoice to this job.: 
- [x]  if invoice && if job.owner or job.assigned_user:  display Edit invoice Button else display Add Invoice Button
- [ ] 
- [ ] 

Story Points = 2
