### ISSUE TITLE
US28: Delete Invoice details on Job Card

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#40]
As an Owner or Assigned person of a Job Card  I can delete an invoice related to a job card  so that I can delete an invoice if a job is cancelled

EPIC #10 

Acceptance criteria
1.   Given that I am the owner of a job - I will see the Delete Invoice Button when I click the Edit Invoice Button
2. Given that I am the assigned_user of a job - I will see the Delete Invoice Button when I click the Edit Invoice Button
3. Given that I have clicked the delete button - the invoice will be deleted and I will see a success message on screen to confirm

Tasks
- [x] Add Delete Button to EditInvoiceForm
- [x] Add handleDelete function to EditInvoiceForm
- [x] Add alerts and success message

Story Points = 2
