### ISSUE TITLE
US33: UX & Testing

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#41]
As a developer, I can test each user story function so that I can verify each function works as intended

EPIC #11 

Acceptance criteria
1. Given that I am a developer I can test each User Story, document failures, fix and test until it passes
2. Given that I am a developer I can write Automated tests on each Model
3. Given that I am a developer I can write Automated tests on each React component
4. Given that I am a developer I will check all code for errors and rectify problems
5. Given that I am a developer all browser-related tests will pass
6. Given that I am a user All pages will follow a consistent design for desktop and mobile

Tasks
- [x] Test all Pages for UX design and consistent layout and design
- [x] Tests for Profile model
- [x] Tests for Job Model
- [x] Tests for Comment Model
- [x] Tests for Invoice Model
- [x] Tests for Watch Model
- [x] Tests for react Components
- [x] Check for any commented-out code
- [x] Lighthouse & accessibility
- [x] W3C CSS Jigsaw Validation - add to Readme
- [x] W3C HTML Validation - add to Readme
- [x] ESLint Validation - add to Readme
- [x] PYLINT Validation - - add to Readme
- [x] ESlint - add to Readme
- [x] Browser Compatibility testing
- [x] Correct indentation
- [x] Check on React Bootstrap5 Accordion and Modal specific CDN libraries
- [x] Check on Nav icons and display with label

Story Points = 4

See Test Sheet - https://docs.google.com/spreadsheets/d/13_KwYGn769y_pbmRmc15LmysJ1FP6jmy4XYWc3TFsfw/edit#gid=545835842

**Comment by rstan-dev** [comment]
jobs view tests written - 19.10

**Comment by rstan-dev** [comment]
Validation and attribute error tests:
In Job Model and Serializer:
You need to ensure that assigned_to can be None (if a job can exist without being assigned to someone). In this case, handle the scenario where assigned_to is None in your serializer.
EG:
assigned_to = serializers.SerializerMethodField()
def get_assigned_to(self, obj):
    return obj.assigned_to.username if obj.assigned_to else None
This modification ensures that if assigned_to is None, the serializer doesn't try to access the username attribute of a non-existent object, which would raise an AttributeError.

**Comment by rstan-dev** [comment]
See warning in JobCard and InvoiceCard due to React Bootstrap 4 Accordian

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
at div
at Transition (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:20950:30)
at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:12453:22
at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:10966:23
at div
at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:11604:23
at div
at https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/vendors~main.chunk.js:10913:96
at div
at div
at div
at div
at div
at JobCard (https://8080-rstandev-garageguru-qf6hm2jbgt7.ws-eu106.gitpod.io/static/js/main.chunk.js:8408:5)

**Comment by rstan-dev** [comment]
Leaving Bootstrap 4 as it is integral to the CI template.  Address in Readme and turn off strict mode.

**Comment by rstan-dev** [comment]
Leaving Nav Icons as is

**Comment by rstan-dev** [comment]
Add isMounted  cleanup functions for all async functions and timout fucntions

// useEffect for handling component mount and unmount
	useEffect(() => {
		return () => {
			isMountedRef.current = false;
			if (successTimeoutRef.current) {
				clearTimeout(successTimeoutRef.current);
			}
		};
	}, []);


- [ ] EditCommentForm
- [ ] RegisterForm
- [ ] AddInvoiceForm
