### ISSUE TITLE
US29: Deploy to Heroku

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#42]
As a developer, I can deploy the project to Heroku  so that I can host the site in production

EPIC #12 

Acceptance criteria
1. Given that I am an end user, I can access the site through a hosted URL
2. Given that I am an end user All functions will work as intended

Tasks
- [x] Follow deployment to Heroku instructions
- [x] Debug set to false
- [x] Update requirements.txt
- [x] Create Procfile
- [x] Manually check all user tests in the deployed version

Story Points = 4
