### ISSUE TITLE
US35: Complete Readme Documentation

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#43]
As a developer can submit a comprehensive Readme document so that other developers can understand the project's development process

EPIC #12 

Tasks
- [x] Readme sections fully completed
- [x] Grammarly checks
- [x] Images check
- [x] Back to links check
- [x] Commented out code check

Story Points = 4
