### ISSUE TITLE
US34: Deploy to Heroku

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#74]
As a developer I can deploy to Heroku so that I can host the site in production

EPIC#12

Acceptance criteria

1. Given that I am an end user, I can access the site through a hosted URL
2.  Given that I am an end user All functions will work as intended 

Tasks
- [x] Follow deployment to Heroku instructions
- [x] Debug set to false
- [x] Update requirements.txt
- [x] Create Procfile
- [x] Manually check all user tests in deployed version"

Story Points = 4

**Comment by rstan-dev** [comment]
Add the Heroku deployment commands

In package.json file, in the “scripts” section, add the following prebuild command:

"heroku-prebuild": "npm install -g serve",
This will install a package needed to serve our single page application on heroku

Add a Procfile at the root of the project with the following web command:

web: serve -s build

**Comment by rstan-dev** [comment]
When combining DRF and React projects: 
Open the axiosDefaults.js file and comment out the baseURL setting

The baseURL is not required during development as the proxy is put in place. This allows the React app to “pretend” it is making requests from the same port as the server and removes cross-domain issues.

To ensure that the API’s routes do not clash with the React application’s routes when we get to deployment, we will set a new path for the API routes in the server and the baseURL. Which is why we are commenting it out, instead of removing it completely.

**Comment by rstan-dev** [comment]
[The following guide](https://code-institute-students.github.io/advfe-unified-workspace/deployment/00-deployment) will assist you in deploying both your React front-end project and your Django API back end.

Setting up WhiteNoise for static files
Because the React part of the project contains static files, we need to store all the static files for deployment, using WhiteNoise. WhiteNoise will also store the static files for the Django Admin panel, so you’ll be able to easily access that from the deployed URL as well.

In the terminal:

Ensure your terminal location is in the root directory, then install whitenoise with the following command

pip3 install whitenoise==6.4.0

Add this dependency to your requirements.txt file with the following command

pip3 freeze > requirements.txt

Create a new empty folder called staticfiles in the root directly with the following command

mkdir staticfiles

a terminal with the command mkdir staticfiles

In settings.py:

In the INSTALLED_APPS list, ensure that the ‘cloudinary_storage’ app name is below ‘django.contrib.staticfiles’. This ensures that Cloudinary will not attempt to intervene with staticfiles, and allows whitenoise to become the primary package responsible for static files

the installed apps section of a settings.py file

In the MIDDLEWARE list, add WhiteNoise below the SecurityMiddleware and above the SessionMiddleware

 'whitenoise.middleware.WhiteNoiseMiddleware',
the MIDDLEWARE section of a settings.py file

In the TEMPLATES list at the DIRS key, add the following code to the DIRS list, to tell Django and WhiteNoise where to look for Reacts index.html file in deployment

 os.path.join(BASE_DIR, 'staticfiles', 'build')
the TEMPLATES section of a settings.py file

In the static files section, add the STATIC_ROOT and WHITENOISE_ROOT variables and values to tell Django and WhiteNoise where to look for the admin static files and Reacts static files during deployment

 STATIC_ROOT = BASE_DIR / 'staticfiles'
 WHITENOISE_ROOT = BASE_DIR / 'staticfiles' / 'build'

**Comment by rstan-dev** [comment]
Configuring the route to allow the React front end to be viewed.

The React front end will be served from the domain’s root URL, so we need to ensure that this is the React part of the project and not the DRF interface you worked with when the projects were separate. So we will add the code below to ensure that the home page will display the React application. Any 404 errors redirect the user back to the React application where the request will be handled by the react-router-dom. We will also adjust our URLs so that all URLs for the DRF API contain /api/ to ensure that the API’s routes do not clash with the React application’s routes.

In the urls.py file of your Django Rest Framework application:

Remove the root_route view from the .views imports

a settings.py file with the root_route import removed

Import the TemplateView from the generic Django views

 from django.views.generic import TemplateView
a settings.py file with a TemplateView import

In the url_patterns list, remove the root_route code and replace it with the TemplateView pointing to the index.html file

 path('', TemplateView.as_view(template_name='index.html')),
Before:

a URL patterns list with root_route next to a blank path

After:

a URL patterns list with a TemplateView next to a blank path

At the bottom of the file, add the 404 handler to allow React to handle 404 errors

 handler404 = TemplateView.as_view(template_name='index.html')
a handler404 variable in a settings.py file

Add api/ to the beginning of all the API URLs, excluding the path for the home page and admin panel

api/ prepended to several URL patterns

In axiosDefault.js:

Now that we have changed the base path for the API route, we need to prepend all API requests in our react application with /api. Open the axiosDefaults.js file, comment back in the axios.defaults.baseURL and set it to "/api"

axios defaults baseurl set with api/

This would be a good point to commit your changes again.

**Comment by rstan-dev** [comment]
[Now that the code for collecting and accessing the static files has been created, we can compile all of the static files from both the Django admin panel and the React files into the staticfiles folder for deployment.](https://code-institute-students.github.io/advfe-unified-workspace/deployment/02-compiling-the-static-files)

Collect the admin and DRF staticfiles to the empty staticfiles directory you created earlier, with the following command in the terminal

python3 manage.py collectstatic

a terminal with the result of the collectstatic command

Next, we will compile the React application and move its files to the staticfiles folder. In another terminal, cd into the frontend directory

cd frontend

a terminal with the result of the cd frontend command

Then run the command to compile and move the React files

npm run build && mv build ../staticfiles/.

the result of a terminal command that compiles and moves the React files

You will need to re-run this command any time you want to deploy changes to the static files in your project, including the React code. To do this, you need to delete the existing build folder and rebuild it.
This command will delete the old folder and replace it with the new one: npm run build && rm -rf ../staticfiles/build && mv build ../staticfiles/.

Now your staticfiles folder should be filled with all the static files needed for deployment

a file structure with a staticfiles directory

Depending on your specific dependency versions, your file structure in the staticfiles folder may be slightly different from the above image. The folders we need to be sure are there are the admin and build folders.

Adding a runtime.txt file
This will ensure Heroku uses the correct version of Python to deploy your project.

In the root directory of your project, create a new file named runtime.txt

Inside the runtime.txt, add the following line:

python-3.9.16

a runtime text file with a single line of text that reads python-3.9.16

**Comment by rstan-dev** [comment]
Advanced Front End: Testing the Build
All our hard work is about to pay off.

Now that all the settings are in place, we can test that the builds for both parts of the project are running together on the same server port.

Ensure all running servers are terminated. In any running terminals press Ctrl+C

In your env.py file, ensure that both the DEBUG and DEV environment variables are commented out

dev and debug variables commented out in an env.py file

Run the Django server, in the terminal type

python3 manage.py runserver

Open the preview on port 8000 to check that your application is running

The React server should not be running. This is a test to check that Django is serving the React static files.

**Comment by rstan-dev** [comment]
These are the final steps. Once completed, your project will be deployed to Heroku.

If you have not deployed this application to Heroku before, you can find most of the steps for this in the Deployment section of the Django REST Framework module. Please ensure that you have added those settings, plus the additional ones below.

Log into your Heroku account and access the dashboard for your DRF application

Go to Settings and open the Config Vars

Ensure your application has an ALLOWED_HOST key, set to the URL of your combined project, remove the https:// at the beginning and remove the trailing slash at the end

Ensure your application has a CLIENT_ORGIN key and set it to the URL of your combined project. This time keep the https:// at the beginning but remove the trailing slash at the end

two config vars on Heroku

If you had a value for CLIENT_ORIGIN before, this would have been for your separate React project deployment on Heroku, now this value needs to be updated to the URL for your combined application.

Ensure all your settings are in place, including the ones from the Deployment section of the Django REST Framework module. Including saving, committing and pushing any changes made to your code

Deploy your application from the Deploy tab in your Heroku dashboard

**Comment by rstan-dev** [comment]
Final User Stories tests passed
