### ISSUE TITLE
US25: Add Invoice Details

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#91]
As an Owner or Assigned person of a Job Card, I can add invoice details to a job card so that a financial record can be maintained

Acceptance criteria

1. Given that I am the owner of a job - I will see the Add Invoice Details Button in the Job Card
2. Given that I am the Assigned user of a job - I will see the Add Invoice Details Button in the Job Card
3. Given that I am a logged in user, I can see placeholder information if no invoice details have been entered yet

Tasks

- [x] Create Invoices model and serilaizer
- [x] Create URLS path
- [x] Add to Admin
- [x] Create View with filter queryset
- [x] Create AddInvoices Component
- [x] Add and link button to AddInvoice page from Job Card
- [x] Create handleSubmit and post invoice linked to a job to api

Story Points = 2

Modify Jobs and Comments Model in drf_api

**Comment by rstan-dev** [comment]
Ensure validation for customer email and phone number
