### ISSUE TITLE
US29: View Invoice Details on AllInvoicesPage

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#92]
As any user of a Job Card, I can view invoice details on the AllInvoicesPage so that I can see the status of the invoices for a job 

EPIC https://github.com/rstan-dev/GarageGuru-PP5/issues/10

Acceptance criteria 

1. Given that I am a logged-in user I can filter by Invoice status, recently updated, and Invoice Due Date, and I can search by Customer Name and Job Number
2. Given that I am a logged-in user I can click a ViewJob button which will open up the relevant Jobcard
3. Given that I am any logged in user, I can see the updated invoice details on a job card

Tasks

- [x] Create InvoicePage
- [x] Create InvoiceCard
- [x] Create AllInvoicesPage
- [x] Fetch Invoices and pass as props to InvoiceCard component
- [x] Fetch Jobs and pass as relatedJob prop to InvoiceCard Component
- [x] Display Invoice Status Block
- [x] Add Filters for Invoice Status
- [x] Add search block and functionality
- [x] Add infinite scroll

Story points 2
