### ISSUE TITLE
US32: Watch Jobs

### ISSUE THREAD

**Issue by rstan-dev** [rstan-dev/GarageGuru-PP5#99]
As a logged-in user, I can click on the eye icon on a job card  so that I can add it to my watch list where I can keep an eye on a job

Epic#

Acceptance criteria

1. Given that I have clicked on the eye icon I will see the job card appear in my Watch Job list
2. Given that I click the eye icon again, it will remove it from my watch Jobs list

Tasks

- [x] Create Watch model
- [x] Create serilaizer
- [x] Create urls
- [x] Add watch_id to job serializer
- [x] Update Jobs Views for watched_by
- [x] Update route filter for watched_by
- [x] write handleWatch and unwatch functionality
- [x] Connect to Eye icon in Jobcard

Storypoints = 2
